name: Auto Unzip Zip File

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip all zip files
        run: |
          mkdir -p unzipped
          for f in *.zip; do
            unzip -o "$f" -d "./unzipped"
          done

      - name: Commit unzipped files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add unzipped
          git commit -m "Auto unzipped zip files"
          git push
