name: Unzip uploaded file

on:
  push:
    paths:
      - '**.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unzip all zip files
        run: |
          for f in *.zip; do
            unzip -o "$f" -d "./unzipped"
          done

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./unzipped
          git commit -m "Auto-unzipped uploaded zip files"
          git push
